version: '2.3'
services:
  proxy:
    container_name: proxy
    build:
      context: .
      target: proxy
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-proxy:${PRODUCT_VERSION}
    environment:
      - DOCSERVICE_HOST_PORT=docservice:8000
      - SPELLCHECKER_HOST_PORT=spellchecker:8080
      - EXAMPLE_HOST_PORT=example:3000
    stdin_open: true
    restart: always
    ports:
      - '80:8888'
#    volumes:
#      - /etc/${COMPANY_NAME}
#      - /var/www/${COMPANY_NAME}/Data
#      - ./var/lib/ds:/var/lib/${COMPANY_NAME}/documentserver/App_Data/cache/files
#      - ./var/lib/example:/var/www/${COMPANY_NAME}/documentserver-example/public/files
#      - /usr/share/fonts
#      - ./http-upstream.conf:/etc/nginx/includes/http-upstream.conf
       
  docservice:
    build:
      context: .
      target: docservice
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-docservice:${PRODUCT_VERSION}
    container_name: docservice
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
      - METRICS_HOST=metrics
      - METRICS_ENABLED=true
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
      - metrics
    stdin_open: true
    restart: always
    expose:
      - '8000'
    volumes_from:
     - proxy

  converter:
    build:
      context: .
      target: converter
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-converter:${PRODUCT_VERSION}
    container_name: converter
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
      - METRICS_HOST=metrics
      - METRICS_ENABLED=true
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
      - metrics
    stdin_open: true
    restart: always
    volumes_from:
     - proxy

  spellchecker:
    build:
      context: .
      target: spellchecker
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-spellchecker:${PRODUCT_VERSION}
    container_name: spellchecker
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
      - METRICS_HOST=metrics
      - METRICS_ENABLED=true
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
      - metrics
    stdin_open: true
    restart: always
    expose:
      - '8080'
    volumes_from:
     - proxy

  metrics:
    build:
      context: .
      target: metrics
    container_name: metrics
    expose:
      - '8125'
      - '8126'
  
  example:
    build:
      context: .
      target: example
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-example:${PRODUCT_VERSION}
    container_name: example
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
    stdin_open: true
    restart: always
    expose:
      - '3000'
    volumes_from:
     - proxy

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - '6379'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  postgresql:
    container_name: postgresql
    build:
      context: .
      target: db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
