version: '3.8'
services:
  proxy:
    container_name: proxy
    build:
      context: .
      target: proxy
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-proxy${PRODUCT_EDITION}:${PRODUCT_VERSION}
    environment:
      - DOCSERVICE_HOST_PORT=docservice:8000
      - SPELLCHECKER_HOST_PORT=spellchecker:8080
      - EXAMPLE_HOST_PORT=example:3000
    stdin_open: true
    restart: always
    ports:
      - '80:8888'
    volumes:
      - common_data:/var/lib/${COMPANY_NAME} 
       
  docservice:
    build:
      context: .
      target: docservice
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-docservice${PRODUCT_EDITION}:${PRODUCT_VERSION}
    container_name: docservice
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
      - METRICS_HOST=metrics
      - METRICS_ENABLED=true
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
      - metrics
    stdin_open: true
    restart: always
    expose:
      - '8000'
    volumes:
     - common_data:/var/lib/${COMPANY_NAME}

  converter:
    build:
      context: .
      target: converter
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-converter${PRODUCT_EDITION}:${PRODUCT_VERSION}
    container_name: converter
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
      - METRICS_HOST=metrics
      - METRICS_ENABLED=true
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
      - metrics
    stdin_open: true
    restart: always
    volumes:
     - common_data:/var/lib/${COMPANY_NAME}

  spellchecker:
    build:
      context: .
      target: spellchecker
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-spellchecker${PRODUCT_EDITION}:${PRODUCT_VERSION}
    container_name: spellchecker
    environment:
      - DB_HOST=postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - REDIST_SERVER_HOST=redis
      - AMQP_HOST=rabbitmq
      - METRICS_HOST=metrics
      - METRICS_ENABLED=true
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
      - metrics
    stdin_open: true
    restart: always
    expose:
      - '8080'
    volumes:
     - common_data:/var/lib/${COMPANY_NAME}

  metrics:
    build:
      context: .
      target: metrics
    container_name: metrics
    expose:
      - '8125'
      - '8126'

  example:
    build:
      context: .
      target: example
    image: ${COMPANY_NAME}/${PRODUCT_NAME}-example${PRODUCT_EDITION}:${PRODUCT_VERSION}
    container_name: example
    environment:
      - JWT_ENABLED=false
      # Uncomment the line below and enter your ONLYOFFICE Docs address
      # - DS_URL=http://onlyoffice-docs-address/
    depends_on:
      - proxy
    stdin_open: true
    restart: always
    expose:
      - '3000'
    volumes:
     - common_data:/var/lib/${COMPANY_NAME}

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - '6379'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  postgresql:
    container_name: postgresql
    build:
      context: .
      target: db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  common_data:
  postgresql_data:
