#!/bin/bash

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
cat /etc/os-release
uname -r
apt install -y wget
apt-get update -y 
apt-get install linux-image-4.8.0-56 -y 
apt install libpipeline1 -y
update-grub -y 
uname -r 
#apt-get install -y qemu-user-static
#apt-get install -y binfmt-support 
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
docker buildx ls
docker buildx bake docservice proxy converter --push  --set *.platform=linux/amd64,linux/arm64
